name: placemark_studio
description: "A KML data manipulation studio"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  xml: ^6.4.2
  path: ^1.9.1
  provider: ^6.1.5
  get_it: ^8.0.3
  injectable: ^2.5.0
  auto_route: ^7.8.4
  freezed: ^2.4.6
  json_serializable: ^6.9.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  archive: ^3.4.9
  mime: ^2.0.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  fl_chart: ^1.0.0
  excel: ^2.1.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
